name: DevOps-GitHubActions
on: push
jobs:
  # Build Job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: 'https://registry.yarnpkg.com'
      - run: npm install -g yarn
      - run: yarn install

      - name: Build Project
        run: yarn run build

      - name: Upload artifact to enable deployment
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./build
  # Deploy Job
  deploy:
    # Add a dependency to the build job
    needs: build
    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.SECRET_GITHUB }}
          publish_dir: ./build
